apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkout-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: linkout.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkout-service
                port:
                  number: 8000
