apiVersion: v1
kind: Service
metadata:
  name: linkout-service
spec:
  selector:
    app: linkout
  ports:
    - protocol: TCP
      port: 8000        # Port interne Kubernetes
      targetPort: 8000  # Port du container
      nodePort: 30001   # Port pour acc√©der via localhost:30001
  type: NodePort
